// Auto-generated by the custom extract_extents Python script — do not edit manually.
// Data source: MEOW (Marine Ecoregions of the World) regions parquet from mermaid.prescient.earth

export const REGION_EXTENTS: Record<string, [number, number, number, number]> = {
  Arctic: [7.1561, 46.3561, 355.4041, 86.9194],
  'Central Indo-Pacific': [93.4884, -34.9659, 193.5472, 31.8309],
  'Eastern Indo-Pacific': [158.9925, -31.2815, 257.8747, 31.5155],
  'Southern Ocean': [0.0106, -89.9, 337.0855, -42.6541],
  'Temperate Australasia': [109.5768, -49.6906, 187.2121, -23.3485],
  'Temperate Northern Atlantic': [258.8503, 19.3856, 338.3166, 72.8595],
  'Temperate Northern Pacific': [112.8948, 20.1863, 258.1686, 66.4515],
  'Temperate South America': [275.4711, -59.3458, 320.4102, -5.0204],
  'Temperate Southern Africa': [8.3232, -42.1056, 80.92, -14.6795],
  'Tropical Atlantic': [258.7786, -25.3381, 357.6819, 35.6785],
  'Tropical Eastern Pacific': [241.8658, -5.9791, 286.3025, 22.8451],
  'Western Indo-Pacific': [29.1411, -29.6989, 103.4213, 33.8765],
}
