name: Deploy

on:
  push:
    branches:
      - develop
    tags:
      - 'v*.*.*'
jobs:
  deploy_develop:
    if: startsWith(github.ref, 'refs/heads/develop')
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      environment: dev
